"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { CHECKOUT_FLOW_STEPS, useCheckout } from "@/components/checkout/CheckoutContext";
import { AiInsightCard } from "@/components/AiInsightCard";
import { PrimaryCTA } from "@/components/PrimaryCTA";
import { StepProgress } from "@/components/StepProgress";
import { Card } from "@/components/ui/Card";
import { PageSkeleton } from "@/components/ui/Skeleton";

export default function CheckoutAiPage() {
  const { deal, sellerTrust, buyerTrust, loading, code } = useCheckout();

  if (loading || !deal) return <PageSkeleton />;

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      <StepProgress steps={[...CHECKOUT_FLOW_STEPS]} currentId="ai" />

      <div>
        <p className="section-label">Theqa AI</p>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight text-navy-900">
          AI fraud insight
        </h1>
        <p className="mt-2 text-sm text-ink-muted">
          Advisory only. AI never calculates Trust Scores and never moves funds.
        </p>
      </div>

      <AiInsightCard
        endpoint="fraud-summary"
        body={{
          deal_id: deal.id,
          title: deal.title,
          amount: deal.amount,
          currency: deal.currency,
          status: deal.status,
          fee_bps: deal.fee_bps,
          seller_score: sellerTrust?.score ?? null,
          buyer_score: buyerTrust?.score ?? null,
        }}
      />

      <Card className="border-dashed p-4 text-xs text-ink-dim">
        Generated by Theqa AI · Trust Score calculated separately by the Trust Engine.
      </Card>

      <PrimaryCTA href={`/checkout/${code}/accept`}>Continue</PrimaryCTA>
      <Link
        href={`/checkout/${code}/trust`}
        className="block text-center text-xs text-ink-dim hover:text-ink"
      >
        Back
      </Link>
    </motion.div>
  );
}
