"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";
import { api } from "@/lib/api";

export type AiInsight = {
  capability: string;
  title: string;
  summary: string;
  bullets: string[];
  risk_level?: string | null;
  source: string;
  disclaimer: string;
};

const RISK_TONE: Record<string, string> = {
  low: "text-brand-700 border-brand-200 bg-brand-50",
  medium: "text-amber-700 border-amber-200 bg-amber-50",
  high: "text-red-700 border-red-200 bg-red-50",
};

export function AiInsightCard({
  endpoint,
  body,
  className = "",
}: {
  endpoint:
    | "trust-explanation"
    | "fraud-summary"
    | "risk-analysis"
    | "merchant-summary"
    | "buyer-guidance";
  body: Record<string, unknown>;
  className?: string;
}) {
  const [insight, setInsight] = useState<AiInsight | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    async function run() {
      setLoading(true);
      try {
        const res = await api<AiInsight>(`/v1/ai/${endpoint}`, {
          method: "POST",
          body: JSON.stringify(body),
        });
        if (!cancelled) setInsight(res);
      } catch {
        if (!cancelled) {
          setInsight({
            capability: endpoint,
            title: "AI insight unavailable",
            summary:
              "Advisory insights could not be loaded. Trust Scores remain calculated by the Trust Engine.",
            bullets: [],
            source: "fallback",
            disclaimer:
              "Generated by Theqa AI · Trust Score calculated separately by the Trust Engine.",
          });
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    void run();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [endpoint, JSON.stringify(body)]);

  return (
    <div className={`ai-gradient-border rounded-2xl p-5 shadow-soft ${className}`}>
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-brand-100 to-sky-100 text-brand-700">
            <Sparkles className="h-4 w-4" />
          </span>
          <div>
            <p className="section-label">Theqa AI</p>
            <p className="text-sm font-semibold text-ink">
              {loading ? "Generating insight…" : insight?.title ?? "Insight"}
            </p>
          </div>
        </div>
        {insight?.risk_level && (
          <span
            className={`rounded-full border px-2.5 py-0.5 text-[10px] font-semibold uppercase ${
              RISK_TONE[insight.risk_level] ?? RISK_TONE.low
            }`}
          >
            {insight.risk_level} risk
          </span>
        )}
      </div>

      {loading ? (
        <div className="mt-4 space-y-2">
          <div className="h-3 animate-pulse rounded-lg bg-canvas-soft" />
          <div className="h-3 w-5/6 animate-pulse rounded-lg bg-canvas-soft" />
          <div className="h-3 w-2/3 animate-pulse rounded-lg bg-canvas-soft" />
        </div>
      ) : (
        <motion.div initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} className="mt-3">
          <p className="text-sm leading-relaxed text-ink-soft">{insight?.summary}</p>
          {insight?.bullets && insight.bullets.length > 0 && (
            <ul className="mt-3 space-y-1.5 text-xs text-ink-muted">
              {insight.bullets.map((b) => (
                <li key={b} className="flex gap-2">
                  <span className="text-brand-600">•</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          )}
          <p className="mt-4 text-[10px] leading-relaxed text-ink-dim">
            {insight?.disclaimer ??
              "Generated by Theqa AI · Trust Score calculated separately by the Trust Engine. AI never moves funds."}
            {insight?.source && insight.source !== "fallback"
              ? ` · via ${insight.source}`
              : " · template"}
          </p>
          <p className="mt-2 font-mono text-[10px] text-ink-dim">
            POST /v1/ai/{endpoint}
          </p>
        </motion.div>
      )}
    </div>
  );
}
