"use client";

import { useEffect, useMemo, useState } from "react";
import {
  api,
  getAccessToken,
  type Deal,
  type MeResponse,
  type TrustScore,
} from "@/lib/api";
import {
  ACTIVE_PURCHASE_STATUSES,
  isMerchantUser,
  nextActionLabel,
  primaryOrg,
} from "@/lib/roles";
import { AppShell, Topbar } from "@/components/AppShell";
import { AiInsightCard } from "@/components/AiInsightCard";
import { Card } from "@/components/ui/Card";
import { PageSkeleton } from "@/components/ui/Skeleton";

/**
 * Dedicated AI hub — live POST /v1/ai/* calls.
 * Never calculates Trust Scores (Trust Engine is separate).
 */
export default function AiInsightsPage() {
  const [me, setMe] = useState<MeResponse | null>(null);
  const [deals, setDeals] = useState<Deal[]>([]);
  const [trust, setTrust] = useState<TrustScore | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      if (!getAccessToken()) {
        window.location.href = "/portal";
        return;
      }
      try {
        const meRes = await api<MeResponse>("/v1/me");
        setMe(meRes);
        setDeals(await api<Deal[]>("/v1/deals"));
        const merchant = meRes.orgs.find((o) => o.type === "merchant");
        const entityType = merchant ? "merchant" : "individual";
        const entityId = merchant ? merchant.id : meRes.user.id;
        try {
          setTrust(
            await api<TrustScore>(`/v1/trust/scores/${entityType}/${entityId}`, { auth: false })
          );
        } catch {
          setTrust(null);
        }
      } finally {
        setLoading(false);
      }
    }
    void load();
  }, []);

  const merchant = isMerchantUser(me);
  const org = primaryOrg(me);

  const stats = useMemo(() => {
    const released = deals.filter((d) => d.status === "released");
    const active = deals.filter((d) =>
      (ACTIVE_PURCHASE_STATUSES as readonly string[]).includes(d.status)
    );
    const volume = released.reduce((s, d) => s + d.amount, 0);
    const sample = active[0] ?? deals[0] ?? null;
    return {
      released: released.length,
      active: active.length,
      volume,
      sample,
    };
  }, [deals]);

  if (loading) {
    return (
      <AppShell>
        <PageSkeleton />
      </AppShell>
    );
  }

  return (
    <AppShell>
      <Topbar
        title="AI Insights"
        subtitle="Live API · Generated by Theqa AI · Trust Score calculated separately by Trust Engine"
      />

      <Card className="mb-6 p-5">
        <p className="section-label">AI data flow</p>
        <p className="mt-2 text-sm text-ink-soft">
          UI → <code className="font-mono text-xs">POST /v1/ai/&lt;capability&gt;</code> → AI
          service → structured insight JSON → cards below. Input is deal/trust context from your
          account; output is advisory only.
        </p>
        <ul className="mt-3 space-y-1.5 text-xs text-ink-muted">
          {merchant ? (
            <>
              <li>
                <span className="font-mono text-navy-900">merchant-summary</span> — product
                performance, pricing hints, demand signals, Trust Score improvement tips
              </li>
              <li>
                <span className="font-mono text-navy-900">risk-analysis</span> — deal-level risk
                before/during fulfillment
              </li>
              <li>
                <span className="font-mono text-navy-900">trust-explanation</span> — explains Trust
                Engine factors (does not change the score)
              </li>
              <li>
                <span className="font-mono text-navy-900">fraud-summary</span> — platform fraud /
                behavior signals (admin/platform use)
              </li>
            </>
          ) : (
            <>
              <li>
                <span className="font-mono text-navy-900">buyer-guidance</span> — need analysis,
                deal recommendations, why a deal fits
              </li>
              <li>
                <span className="font-mono text-navy-900">risk-analysis</span> — price/quality risk
                before purchase
              </li>
              <li>
                <span className="font-mono text-navy-900">fraud-summary</span> — counterparty risk
                flags
              </li>
              <li>
                <span className="font-mono text-navy-900">trust-explanation</span> — why your buyer
                Trust Score looks the way it does
              </li>
            </>
          )}
        </ul>
        <p className="mt-3 text-[11px] text-ink-dim">
          AI never moves funds, never holds money, and never calculates Trust Scores.
        </p>
      </Card>

      <div className="mx-auto grid max-w-2xl gap-4">
        {merchant ? (
          <>
            <AiInsightCard
              endpoint="merchant-summary"
              body={{
                org_name: org?.name,
                trust_score: trust?.score ?? null,
                active_deals: stats.active,
                released_deals: stats.released,
                volume: stats.volume,
              }}
            />
            <AiInsightCard
              endpoint="trust-explanation"
              body={{
                entity_type: "merchant",
                entity_id: org?.id,
                score: trust?.score ?? null,
                breakdown: trust?.breakdown ?? null,
              }}
            />
            {stats.sample && (
              <AiInsightCard
                endpoint="risk-analysis"
                body={{
                  deal_id: stats.sample.id,
                  title: stats.sample.title,
                  amount: stats.sample.amount,
                  currency: stats.sample.currency,
                  status: stats.sample.status,
                  fee_bps: stats.sample.fee_bps,
                }}
              />
            )}
            {stats.sample && (
              <AiInsightCard
                endpoint="fraud-summary"
                body={{
                  deal_id: stats.sample.id,
                  title: stats.sample.title,
                  amount: stats.sample.amount,
                  currency: stats.sample.currency,
                  status: stats.sample.status,
                  fee_bps: stats.sample.fee_bps,
                  seller_score: trust?.score ?? null,
                  buyer_score: null,
                }}
              />
            )}
          </>
        ) : (
          <>
            <AiInsightCard
              endpoint="buyer-guidance"
              body={{
                trust_score: trust?.score ?? null,
                active_purchases: stats.active,
                next_action: stats.sample
                  ? nextActionLabel(stats.sample.status, "buyer")
                  : "Open a merchant checkout link",
                deal_status: stats.sample?.status ?? null,
              }}
            />
            <AiInsightCard
              endpoint="trust-explanation"
              body={{
                entity_type: "individual",
                entity_id: me?.user.id,
                score: trust?.score ?? null,
                breakdown: trust?.breakdown ?? null,
              }}
            />
            {stats.sample && (
              <AiInsightCard
                endpoint="risk-analysis"
                body={{
                  deal_id: stats.sample.id,
                  title: stats.sample.title,
                  amount: stats.sample.amount,
                  currency: stats.sample.currency,
                  status: stats.sample.status,
                  fee_bps: stats.sample.fee_bps,
                }}
              />
            )}
            {stats.sample && (
              <AiInsightCard
                endpoint="fraud-summary"
                body={{
                  deal_id: stats.sample.id,
                  title: stats.sample.title,
                  amount: stats.sample.amount,
                  currency: stats.sample.currency,
                  status: stats.sample.status,
                  fee_bps: stats.sample.fee_bps,
                  seller_score: null,
                  buyer_score: trust?.score ?? null,
                }}
              />
            )}
          </>
        )}
      </div>
    </AppShell>
  );
}
